apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  targetType: ip
  serviceRef:
    name: frontend # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:211116633177:targetgroup/k8s-roboshop-frontend-571b457fd7/94d9a40265d25668