configMap:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "roboshop-dev.ca1uqacqqh13.us-east-1.rds.amazonaws.com"
deployment:
  replicas: "1"
  imageName: "sam123yuktha/shipping"
  imageVersion: "1.4.0"
hpa:
  minReplicas: "1"
  maxReplicas: "10"
  targetCPUUtilizationPercentage: "60"