deployment:
  replicas: "1"
  imageName: "sam123yuktha/frontend"
  imageVersion: "1.4.0"
ingress:
  host: "roboshop-dev.dev88s.online"
hpa:
  minReplicas: "1"
  maxReplicas: "10"
  targetCPUUtilizationPercentage: "60"